export const RESULTS_LOAD = 'RESULTS_LOAD';

export const VOTING_FORM_ADDRESS_CHANGE = 'VOTING_FORM_ADDRESS_CHANGE';
export const VOTING_FORM_LOCATION_CHANGE = 'VOTING_FORM_LOCATION_CHANGE';
export const VOTING_FORM_SUPPORTS_CANDIDATE_CHANGE = 'VOTING_FORM_SUPPORTS_CANDIDATE_CHANGE';
export const VOTING_FORM_RESET = 'VOTING_FORM_RESET';
